name: Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for semantic-release

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install semantic-release
        run: |
          npm install -g @semantic-release/commit-analyzer@12.0.0 \
          @semantic-release/release-notes-generator@13.0.0 \
          @semantic-release/exec@6.0.3 \
          @semantic-release/github@10.0.7 \
          semantic-release@23.1.1 \
          conventional-changelog-conventionalcommits@7.0.2

      - name: Release
        id: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release